### ISSUE TITLE
ETA on deployment?

### ISSUE THREAD

**Issue by battlemidget** [canonical-websites/conjure-up.io#11]
Hi!

When can we expect this website to go live?

**Comment by pmahnke** [comment]
@battlemidget 

It is waiting on an IS [RT](https://portal.admin.canonical.com/101097) we have put our highest priority on it, but it has been sitting for since 22 March.

Really sorry,

Peter

**Comment by battlemidget** [comment]
Thanks for the quick update Peter, I'll follow along with that RT
