### ISSUE TITLE
2017-03-14: Conjure-up briefing

### ISSUE THREAD

**Issue by grahambancroft** [canonical-websites/conjure-up.io#2]
_Attendees: @magdalena-mirowicz @joanasa89 @WillMoggridge @grahambancroft @battlemidget @Greggless

- Target audience: individuals that don't understand conjure-up, three step approach is good but @battlemidget prefers the general hero approach
- No need for spell list as terminal lists all spells but add third item with instructions on how to get this list
- docs moving to docs.ubuntu.com - @battlemidget to have permission to deploy
- No need for old blog content to be migrated to insights.ubuntu.com but we can link to insights articles where appropriate 
- We need to let @battlemidget know when there’s a demo available

**Comment by Greggless** [comment]
Conjure-up.io wireframe proposal

![conjure-up io](https://cloud.githubusercontent.com/assets/23459065/23942857/7f7e0564-0965-11e7-9199-3167e310f9c5.jpg)

**Comment by battlemidget** [comment]
Looks good to me!

**Comment by anthonydillon** [comment]
Looks good. I like the spells section. I wonder if the spells section
should be cards and the getting help section could be divided as the store
is using cards to display product/items.

**Comment by Greggless** [comment]
@anthonydillon . Thanks for the feedback

@joanasa89 what are you visual design thoughts on this? It's a good rationale and I see no objection to making the change...

**Comment by joanasa89** [comment]
@Greggless @anthonydillon yes, I am ok with that.

**Comment by Greggless** [comment]
Closing issue

@joanasa89 could you update the final design in code pretty please
