### ISSUE TITLE
website still points to rocketchat

### ISSUE THREAD

**Issue by battlemidget** [canonical-websites/conjure-up.io#34]
I could've sworn the website was recently updated about the change from rocketchat to irc, but going there now shows rocketchat.

Was this change pushed live yet or am i remembering it wrong? This issue is what triggered me to look: https://github.com/conjure-up/conjure-up/issues/1411

Thanks!

**Comment by anthonydillon** [comment]
Sorry @battlemidget the site had not been released since the branch landed. I've pushed it live now.
