### ISSUE TITLE
Search never returns any results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/conjure-up.io#35]
1\. Go to [the Conjure-up user manual](https://docs.conjure-up.io/2.4.0/en/) or [the developer manual](https://docs.conjure-up.io/2.4.0/en/dev-manual).
2\. Enter anything in the search field that you know is present in either of the manuals. For example, “[metadata](https://docs.ubuntu.com/search?q=metadata&domain=docs.conjure-up.io)”, “[cloud selection](https://docs.ubuntu.com/search?q=cloud+selection&domain=docs.conjure-up.io)”, or “[bitbucket](https://docs.ubuntu.com/search?q=bitbucket&domain=docs.conjure-up.io)”.

What happens: “Your search … returned 0 results”

What should happen: Your search returns results.

**Comment by anasereijo** [comment]
@nottrobin is this something you can have a look at?
