### ISSUE TITLE
Stylesheets not working at canonical-websites.github.io/conjure-up.io

### ISSUE THREAD

**Issue by theel0ja** [canonical-websites/conjure-up.io#4]
https://canonical-websites.github.io/conjure-up.io/

`<link rel="stylesheet" href="/css/main.css">` is going to https://canonical-websites.github.io/css/main.css, so it should be `<link rel="stylesheet" href="./css/main.css">`.

**Comment by WillMoggridge** [comment]
Thanks for pointing this out. We wanted to use GitHub pages to demo the website while we waited for other options. We now have a staging server available, so we may remove the GitHub pages features.

I will keep this open until we make a move either way.

**Comment by WillMoggridge** [comment]
We have decided to remove the Github pages from this project as we won't be using it. Thanks for the issue, I will close it now.
